/* eslint-disable eslint-comments/no-unlimited-disable */

/* eslint-disable */

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/~__root'
import { Route as IndexRouteImport } from './routes/~index'
import { Route as TaskIdEditRouteImport } from './routes/~task/~$id/~edit'
import { Route as TaskIdIndexRouteImport } from './routes/~task/~$id/~index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TaskIdEditRoute = TaskIdEditRouteImport.update({
  id: '/task/$id/edit',
  path: '/task/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const TaskIdIndexRoute = TaskIdIndexRouteImport.update({
  id: '/task/$id/',
  path: '/task/$id/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/task/$id': typeof TaskIdIndexRoute
  '/task/$id/edit': typeof TaskIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/task/$id': typeof TaskIdIndexRoute
  '/task/$id/edit': typeof TaskIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/task/$id/': typeof TaskIdIndexRoute
  '/task/$id/edit': typeof TaskIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/task/$id' | '/task/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/task/$id' | '/task/$id/edit'
  id: '__root__' | '/' | '/task/$id/' | '/task/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TaskIdIndexRoute: typeof TaskIdIndexRoute
  TaskIdEditRoute: typeof TaskIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/task/$id/edit': {
      id: '/task/$id/edit'
      path: '/task/$id/edit'
      fullPath: '/task/$id/edit'
      preLoaderRoute: typeof TaskIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/task/$id/': {
      id: '/task/$id/'
      path: '/task/$id'
      fullPath: '/task/$id'
      preLoaderRoute: typeof TaskIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TaskIdIndexRoute: TaskIdIndexRoute,
  TaskIdEditRoute: TaskIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
