name = "tasks-app"
main = "src/app.ts"
compatibility_date = "2024-12-05"
compatibility_flags = [ "nodejs_compat" ]

[assets]
directory = "public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "tasks-app-db-sg"
database_id = "4c2d0d93-0d0d-47e1-9a15-7493f9775f8b"
migrations_dir = "src/db/migrations"

[vars]
LOG_LEVEL = "debug"
GITHUB_CLIENT_ID = "your-client-id-here"
GITHUB_CLIENT_SECRET = "your-client-secret-here"
AUTH_SECRET = "abc123"
AUTH_URL = "http://localhost:5173/api/auth"
