name = "tasks-app"
main = "src/app.ts"
compatibility_date = "2024-12-05"
compatibility_flags = [ "nodejs_compat" ]

[assets]
directory = "public"
binding = "ASSETS"

[vars]
LOG_LEVEL = "debug"
GITHUB_CLIENT_ID = "your-github-client-id"
GITHUB_CLIENT_SECRET = "your-github-client-secret"
AUTH_SECRET = "abc123"
AUTH_URL = "http://localhost:5173/api/auth"
